send_light_mode:
  name: Nature Remo Light Mode
  description: Send command to the selected light using button name.
  target:
    entity:
      domain: light
  fields:
    mode:
      name: Mode
      description: Select or input the desired mode (e.g., on, night).
      required: true
      example: night
      selector:
        select:
          options:
            - 'on'
            - 'on-100'
            - 'on-favorite'
            - 'night'
            - 'bright-up'
            - 'bright-down'
            - 'colortemp-up'
            - 'colortemp-down'
          custom_value: true

learn_signal:
  name: Nature Remo Learn Signal
  description: Start learning an infrared signal.
  fields:
    appliance_id:
      name: Appliance ID
      description: Appliance ID to learn a signal for
      required: true
      example: "abc123-def456"
      selector:
        text:
